"""add country state_province pin_code to users

Revision ID: 284fb70fd322
Revises: 0c534a0b0ea6
Create Date: 2026-09-11 21:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '284fb70fd322'
down_revision: str | None = '0c534a0b0ea6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Sentinel backfill values for any pre-existing rows created before this feature.
# These are placeholders only ("unknown"); the profile-edit flow (User Story 5)
# lets an existing account set its real country/state/pin at any time.
_BACKFILL_COUNTRY = "US"
_BACKFILL_STATE = "CA"
_BACKFILL_PIN = "00000"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Added nullable first so existing rows can be safely backfilled before the
    # NOT NULL constraint is applied (per data-model.md migration note).
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state_province', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('pin_code', sa.String(length=12), nullable=True))

    op.execute(
        f"UPDATE users SET country = '{_BACKFILL_COUNTRY}', "
        f"state_province = '{_BACKFILL_STATE}', pin_code = '{_BACKFILL_PIN}' "
        "WHERE country IS NULL"
    )

    op.alter_column('users', 'country', existing_type=sa.String(length=100), nullable=False)
    op.alter_column('users', 'state_province', existing_type=sa.String(length=100), nullable=False)
    op.alter_column('users', 'pin_code', existing_type=sa.String(length=12), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_code')
    op.drop_column('users', 'state_province')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
