"""add profile security fields (encryption, verification, recovery)

Revision ID: 3f9a2c6b1d40
Revises: 284fb70fd322
Create Date: 2026-09-25 09:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.core.encryption import blind_index, decrypt_field, encrypt_field
from src.core.security import hash_password

# revision identifiers, used by Alembic.
revision: str = '3f9a2c6b1d40'
down_revision: str | None = '284fb70fd322'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Sentinel backfill values for any pre-existing rows created before this feature. These
# are placeholders only; there is no way to recover a real DOB/security answer for
# accounts that registered before these fields existed. Existing users are also left
# unverified (`is_verified=False`) since they never completed the new OTP flow.
_BACKFILL_DOB = "1970-01-01"
_BACKFILL_SECURITY_QUESTION_CODE = "FIRST_PET"
_BACKFILL_SECURITY_ANSWER = "unknown"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number_new', sa.String(length=255), nullable=True))
    op.add_column(
        'users', sa.Column('mobile_number_lookup_hash', sa.String(length=64), nullable=True)
    )
    op.add_column(
        'users', sa.Column('date_of_birth_encrypted', sa.String(length=255), nullable=True)
    )
    op.add_column('users', sa.Column('security_question_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('security_answer_hash', sa.String(length=255), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'users', sa.Column('recovery_locked_until', sa.DateTime(timezone=True), nullable=True)
    )

    # --- Data migration: encrypt existing plaintext mobile_number values and backfill
    # the new required columns for any pre-existing rows. ---
    bind = op.get_bind()
    users_table = sa.table(
        'users',
        sa.column('id', sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.column('mobile_number', sa.String),
        sa.column('mobile_number_new', sa.String),
        sa.column('mobile_number_lookup_hash', sa.String),
        sa.column('date_of_birth_encrypted', sa.String),
        sa.column('security_question_code', sa.String),
        sa.column('security_answer_hash', sa.String),
    )
    encrypted_backfill_dob = encrypt_field(_BACKFILL_DOB)
    hashed_backfill_answer = hash_password(_BACKFILL_SECURITY_ANSWER)
    rows = bind.execute(sa.select(users_table.c.id, users_table.c.mobile_number)).fetchall()
    for row in rows:
        bind.execute(
            users_table.update()
            .where(users_table.c.id == row.id)
            .values(
                mobile_number_new=encrypt_field(row.mobile_number),
                mobile_number_lookup_hash=blind_index(row.mobile_number),
                date_of_birth_encrypted=encrypted_backfill_dob,
                security_question_code=_BACKFILL_SECURITY_QUESTION_CODE,
                security_answer_hash=hashed_backfill_answer,
            )
        )

    op.drop_index('ix_users_mobile_number', table_name='users')
    op.drop_column('users', 'mobile_number')
    op.alter_column('users', 'mobile_number_new', new_column_name='mobile_number')

    op.alter_column('users', 'mobile_number', existing_type=sa.String(length=255), nullable=False)
    op.alter_column(
        'users', 'mobile_number_lookup_hash', existing_type=sa.String(length=64), nullable=False
    )
    op.alter_column(
        'users', 'date_of_birth_encrypted', existing_type=sa.String(length=255), nullable=False
    )
    op.alter_column(
        'users', 'security_question_code', existing_type=sa.String(length=50), nullable=False
    )
    op.alter_column(
        'users', 'security_answer_hash', existing_type=sa.String(length=255), nullable=False
    )

    op.create_index(
        op.f('ix_users_mobile_number_lookup_hash'),
        'users',
        ['mobile_number_lookup_hash'],
        unique=True,
    )
    op.alter_column('users', 'is_verified', server_default=None)

    op.create_table(
        'email_verification_codes',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('code_hash', sa.String(length=255), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_used', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_email_verification_codes_user_id'),
        'email_verification_codes',
        ['user_id'],
        unique=False,
    )
    op.alter_column('email_verification_codes', 'attempt_count', server_default=None)
    op.alter_column('email_verification_codes', 'is_used', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_email_verification_codes_user_id'), table_name='email_verification_codes'
    )
    op.drop_table('email_verification_codes')

    op.drop_index(op.f('ix_users_mobile_number_lookup_hash'), table_name='users')

    bind = op.get_bind()
    users_table = sa.table(
        'users',
        sa.column('id', sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.column('mobile_number', sa.String),
        sa.column('mobile_number_plain', sa.String),
    )
    op.add_column('users', sa.Column('mobile_number_plain', sa.String(length=20), nullable=True))
    rows = bind.execute(sa.select(users_table.c.id, users_table.c.mobile_number)).fetchall()
    for row in rows:
        bind.execute(
            users_table.update()
            .where(users_table.c.id == row.id)
            .values(mobile_number_plain=decrypt_field(row.mobile_number))
        )

    op.drop_column('users', 'mobile_number')
    op.alter_column('users', 'mobile_number_plain', new_column_name='mobile_number')
    op.alter_column('users', 'mobile_number', existing_type=sa.String(length=20), nullable=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)

    op.drop_column('users', 'recovery_locked_until')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'security_answer_hash')
    op.drop_column('users', 'security_question_code')
    op.drop_column('users', 'date_of_birth_encrypted')
    op.drop_column('users', 'mobile_number_lookup_hash')
    # ### end Alembic commands ###
