name: CI

on:
  push:
    branches: ['*']
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
    backend:
        name: Backend Build
        runs-on: self-hosted
        timeout-minutes: 15
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: build backend container
              run: docker build --target ci -t backend-ci -f backend/Dockerfile backend

            - name: lint backend code
              run: docker run --rm backend-ci uv run ruff check . --output-format=github


    frontend:
        name: Frontend Build
        runs-on: self-hosted
        timeout-minutes: 15
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: build frontend container
              run: docker build --target ci -t frontend-ci -f frontend/Dockerfile frontend

            - name: lint frontend code
              run: docker run --rm frontend-ci npm run lint